export type Course = {
  slug: string;
  title: string;
  category: "Design" | "Development" | "AI/ML" | "Business" | "Marketing";
  instructor: string;
  duration: string;
  lessons: number;
  students: string;
  rating: number;
  level: "Beginner" | "Intermediate" | "Advanced" | "All Levels";
  emoji: string;
  previewVideoUrl: string;
  shortDescription: string;
  longDescription: string;
  skills: string[];
  isFree?: boolean;
  isHidden?: boolean;
  img?: string;
  color?: string;
  iconPath?: string;
  price: {
    oneMonth: number;
    threeMonth: number;
    sixMonth: number;
  };
};

export const coursesData: Course[] = [
  // ── FREE COURSES ──────────────────────────────────────────────────────────
  {
    slug: "frontend-fundamentals-free",
    title: "Frontend Fundamentals (Free)",
    category: "Development",
    instructor: "Chirantan Biswas",
    duration: "18h",
    lessons: 42,
    students: "23.1K",
    rating: 4.9,
    level: "Beginner",
    emoji: "🌐",
    isFree: true,
    img: "https://images.unsplash.com/photo-1547658719-da2b51169166?q=80&w=800&auto=format&fit=crop",
    color: "from-blue-400 to-indigo-600",
    iconPath: "M12 2L2 7l10 5 10-5-10-5z",
    previewVideoUrl: "https://www.youtube.com/embed/qz0aGYrrlhU",
    shortDescription: "Learn HTML, CSS & JavaScript from scratch. Completely free.",
    longDescription:
      "Build a solid foundation with semantic HTML5, modern CSS layouts (Flexbox, Grid), and JavaScript ES6+. By the end, you'll create responsive websites from scratch with no prior experience needed.",
    skills: ["HTML5", "CSS3", "JavaScript", "Responsive Design"],
    price: { oneMonth: 0, threeMonth: 0, sixMonth: 0 },
  },
  {
    slug: "backend-basics-free",
    title: "Backend Basics with Node.js (Free)",
    category: "Development",
    instructor: "Ryan Torres",
    duration: "14h",
    lessons: 35,
    students: "18.6K",
    rating: 4.8,
    level: "Beginner",
    emoji: "⚙️",
    isFree: true,
    img: "https://images.unsplash.com/photo-1623282033815-40b05d96c903?q=80&w=800&auto=format&fit=crop",
    color: "from-slate-600 to-slate-900",
    iconPath: "M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z",
    previewVideoUrl: "https://www.youtube.com/embed/Oe421EPjeBE",
    shortDescription: "Build REST APIs with Node.js and Express. No cost, no catch.",
    longDescription:
      "Understand the server side: HTTP fundamentals, REST API design, Express.js routing, middleware, database connections with MongoDB, and basic authentication. Learn what powers every web application.",
    skills: ["Node.js", "Express", "REST APIs", "MongoDB"],
    price: { oneMonth: 0, threeMonth: 0, sixMonth: 0 },
  },
  {
    slug: "gen-ai-essentials-free",
    title: "Generative AI Essentials (Free)",
    category: "AI/ML",
    instructor: "Dr. Sarah Park",
    duration: "10h",
    lessons: 24,
    students: "31.4K",
    rating: 4.9,
    level: "All Levels",
    emoji: "🤖",
    isFree: true,
    img: "https://images.unsplash.com/photo-1676299081847-824916de030a?q=80&w=800&auto=format&fit=crop",
    color: "from-violet-500 to-indigo-800",
    iconPath: "M12 1v22M17 5H7M17 19H7M12 5l-5 5 5 5",
    previewVideoUrl: "https://www.youtube.com/embed/aircAruvnKk",
    shortDescription: "Understand LLMs, prompt engineering & AI tools. Completely free.",
    longDescription:
      "Demystify generative AI: how LLMs work, prompt engineering patterns, RAG pipelines, AI agents, and practical tools like ChatGPT, Claude, and Gemini. Build real AI-powered mini-projects by the end.",
    skills: ["Prompt Engineering", "LLMs", "AI Agents", "RAG"],
    price: { oneMonth: 0, threeMonth: 0, sixMonth: 0 },
  },
  // ── PAID COURSES ──────────────────────────────────────────────────────────
  {
    slug: "complete-ui-ux-design-bootcamp",
    title: "Complete UI/UX Design Bootcamp",
    category: "Design",
    instructor: "Gunjan Basak",
    duration: "48h",
    lessons: 120,
    students: "12.4K",
    rating: 4.9,
    level: "Beginner",
    emoji: "🎨",
    img: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=800&auto=format&fit=crop",
    color: "from-pink-400 to-rose-600",
    iconPath: "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z",
    previewVideoUrl: "https://www.youtube.com/embed/c9Wg6Cb_YlU",
    shortDescription: "Master UI/UX from fundamentals to portfolio-ready projects.",
    longDescription:
      "Learn wireframing, visual systems, user flows, prototyping, usability testing, and complete end-to-end case studies. Build portfolio projects reviewed by industry mentors.",
    skills: ["Figma", "Design Systems", "User Research", "Prototyping"],
    price: { oneMonth: 19, threeMonth: 49, sixMonth: 89 },
  },
  {
    slug: "react-nextjs-mastery-2026",
    title: "React & Next.js Mastery 2026",
    category: "Development",
    instructor: "Chirantan Biswas",
    duration: "62h",
    lessons: 155,
    students: "9.8K",
    rating: 4.8,
    level: "Intermediate",
    emoji: "⚛️",
    img: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=800&auto=format&fit=crop",
    color: "from-blue-600 to-indigo-900",
    iconPath: "M12 2L2 7l10 5 10-5-10-5z",
    previewVideoUrl: "https://www.youtube.com/embed/37vxWr0WgQk",
    shortDescription: "Build production-grade React and Next.js apps with TypeScript.",
    longDescription:
      "Cover React architecture, App Router, server components, API routes, performance optimization, and deployment workflows for real-world production apps.",
    skills: ["React", "Next.js", "TypeScript", "API Design"],
    price: { oneMonth: 29, threeMonth: 79, sixMonth: 139 },
  },
  {
    slug: "ai-machine-learning-for-designers",
    title: "AI & Machine Learning for Designers",
    category: "AI/ML",
    instructor: "Dr. Sarah Park",
    duration: "40h",
    lessons: 96,
    students: "7.2K",
    rating: 4.9,
    level: "All Levels",
    emoji: "🤖",
    img: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop",
    color: "from-purple-500 to-indigo-700",
    iconPath: "M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z",
    previewVideoUrl: "https://www.youtube.com/embed/aircAruvnKk",
    shortDescription: "Use modern AI workflows to improve design outcomes.",
    longDescription:
      "Understand practical ML concepts, prompt engineering, AI-assisted UX research, content generation pipelines, and prototyping with LLM-powered interfaces.",
    skills: ["Prompt Design", "AI Workflows", "LLMs", "Automation"],
    price: { oneMonth: 119, threeMonth: 309, sixMonth: 569 },
  },
  {
    slug: "mobile-app-design-with-figma",
    title: "Mobile App Design with Figma",
    category: "Design",
    instructor: "Marcus Lee",
    duration: "32h",
    lessons: 80,
    students: "6.1K",
    rating: 4.7,
    level: "Beginner",
    emoji: "📱",
    img: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=800&auto=format&fit=crop",
    color: "from-orange-400 to-red-600",
    iconPath: "M12 1v22M17 5H7M17 19H7M12 5l-5 5 5 5",
    previewVideoUrl: "https://www.youtube.com/embed/FTFaQWZBqQ8",
    shortDescription: "Design polished mobile interfaces and interactions in Figma.",
    longDescription:
      "Design iOS and Android app flows, create reusable components, build interactive prototypes, and validate UI decisions with rapid usability feedback.",
    skills: ["Mobile UI", "Figma", "Interaction Design", "Design Tokens"],
    price: { oneMonth: 79, threeMonth: 199, sixMonth: 359 },
  },
  {
    slug: "full-stack-development-accelerator",
    title: "Full-Stack Development Accelerator",
    category: "Development",
    instructor: "Ryan Torres",
    duration: "80h",
    lessons: 200,
    students: "11.3K",
    rating: 4.8,
    level: "Advanced",
    emoji: "🔥",
    img: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=800&auto=format&fit=crop",
    color: "from-emerald-400 to-cyan-600",
    iconPath: "M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z",
    previewVideoUrl: "https://www.youtube.com/embed/2OHbjep_WjQ",
    shortDescription: "Build and deploy full-stack applications from scratch.",
    longDescription:
      "Create scalable systems with backend APIs, databases, auth, CI/CD, cloud deployment, and monitoring. Ship real projects suitable for hiring pipelines.",
    skills: ["Node.js", "Databases", "Cloud Deploy", "System Design"],
    price: { oneMonth: 149, threeMonth: 389, sixMonth: 719 },
  },
  {
    slug: "product-management-fundamentals",
    title: "Product Management Fundamentals",
    category: "Business",
    instructor: "Emily Watson",
    duration: "28h",
    lessons: 70,
    students: "4.8K",
    rating: 4.6,
    level: "Beginner",
    emoji: "📊",
    img: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800&auto=format&fit=crop",
    color: "from-blue-400 to-indigo-600",
    iconPath: "M12 2L2 7l10 5 10-5-10-5z",
    previewVideoUrl: "https://www.youtube.com/embed/4vA-_8x3r8U",
    shortDescription: "Learn product strategy, roadmapping, and execution basics.",
    longDescription:
      "Master problem discovery, opportunity sizing, roadmap prioritization, stakeholder communication, and measuring product impact with practical templates.",
    skills: ["Product Strategy", "Roadmapping", "Agile", "Metrics"],
    price: { oneMonth: 69, threeMonth: 179, sixMonth: 319 },
  },
  {
    slug: "advanced-motion-design-framer",
    title: "Advanced Motion Design with Framer",
    category: "Design",
    instructor: "Nina Kaur",
    duration: "24h",
    lessons: 58,
    students: "3.6K",
    rating: 4.7,
    level: "Intermediate",
    emoji: "✨",
    img: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    color: "from-pink-500 to-indigo-600",
    iconPath: "M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z",
    previewVideoUrl: "https://www.youtube.com/embed/1vX4QX0nYlM",
    shortDescription: "Create immersive UI motion with Framer and modern principles.",
    longDescription:
      "Design smooth, performant motion systems for web interfaces, build reusable animation components, and craft premium interaction patterns.",
    skills: ["Framer Motion", "Micro-interactions", "Animation Systems", "UX Motion"],
    price: { oneMonth: 74, threeMonth: 189, sixMonth: 339 },
  },
  {
    slug: "python-for-data-analysis",
    title: "Python for Data Analysis",
    category: "AI/ML",
    instructor: "Arjun Patel",
    duration: "36h",
    lessons: 92,
    students: "8.1K",
    rating: 4.8,
    level: "Beginner",
    emoji: "🐍",
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop",
    color: "from-blue-500 to-teal-400",
    iconPath: "M12 1v22M17 5H7M17 19H7M12 5l-5 5 5 5",
    previewVideoUrl: "https://www.youtube.com/embed/r-uOLxNrNk8",
    shortDescription: "Analyze, visualize, and model real datasets with Python.",
    longDescription:
      "Work through practical data analysis workflows including preprocessing, visualization, exploratory analysis, and basic predictive modeling.",
    skills: ["Python", "Pandas", "Data Visualization", "Statistics"],
    price: { oneMonth: 84, threeMonth: 219, sixMonth: 399 },
  },
  {
    slug: "growth-marketing-playbook",
    title: "Growth Marketing Playbook",
    category: "Marketing",
    instructor: "Leah Kim",
    duration: "22h",
    lessons: 54,
    students: "5.2K",
    rating: 4.6,
    level: "All Levels",
    emoji: "📈",
    img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop",
    color: "from-indigo-400 to-blue-600",
    iconPath: "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z",
    previewVideoUrl: "https://www.youtube.com/embed/zMIt7w6QW7s",
    shortDescription: "Build repeatable growth loops across channels and funnels.",
    longDescription:
      "Plan acquisition campaigns, optimize conversion funnels, run experiments, and track ROI with structured growth frameworks used by top startups.",
    skills: ["Performance Marketing", "Funnel Design", "A/B Testing", "Analytics"],
    price: { oneMonth: 72, threeMonth: 185, sixMonth: 329 },
  },
  {
    slug: "system-design-for-frontend-engineers",
    title: "System Design for Frontend Engineers",
    category: "Development",
    instructor: "Diego Martins",
    duration: "30h",
    lessons: 76,
    students: "4.4K",
    rating: 4.7,
    level: "Advanced",
    emoji: "🧩",
    img: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=800&auto=format&fit=crop",
    color: "from-slate-700 to-indigo-900",
    iconPath: "M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z",
    previewVideoUrl: "https://www.youtube.com/embed/bUHFg8CZFws",
    shortDescription: "Architect scalable, maintainable frontend systems.",
    longDescription:
      "Learn architecture decisions, state modeling, caching, rendering strategies, and performance trade-offs for complex frontend applications.",
    skills: ["Frontend Architecture", "Performance", "State Management", "Scalability"],
    price: { oneMonth: 94, threeMonth: 245, sixMonth: 449 },
  },
  {
    slug: "ux-research-interview-lab",
    title: "UX Research Interview Lab",
    category: "Design",
    instructor: "Olivia Harper",
    duration: "18h",
    lessons: 42,
    students: "2.9K",
    rating: 4.8,
    level: "Intermediate",
    emoji: "🧠",
    img: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=800&auto=format&fit=crop",
    color: "from-emerald-400 to-teal-700",
    iconPath: "M12 1v22M17 5H7M17 19H7M12 5l-5 5 5 5",
    previewVideoUrl: "https://www.youtube.com/embed/3Qz7x2M8y0E",
    shortDescription: "Run user interviews and convert insights into product actions.",
    longDescription:
      "Design research plans, conduct high-quality interviews, synthesize findings, and create actionable reports to influence roadmap decisions.",
    skills: ["User Interviews", "Research Ops", "Insight Synthesis", "UX Strategy"],
    price: { oneMonth: 68, threeMonth: 169, sixMonth: 299 },
  },
  {
    slug: "no-code-ai-automation",
    title: "No-Code AI Automation",
    category: "AI/ML",
    instructor: "Kevin Roy",
    duration: "20h",
    lessons: 48,
    students: "6.8K",
    rating: 4.7,
    level: "All Levels",
    emoji: "⚙️",
    img: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=800&auto=format&fit=crop",
    color: "from-violet-400 to-purple-800",
    iconPath: "M12 2L2 7l10 5 10-5-10-5z",
    previewVideoUrl: "https://www.youtube.com/embed/4M9YQ8jX6gA",
    shortDescription: "Automate workflows with no-code tools and AI integrations.",
    longDescription:
      "Build practical AI automations using popular no-code platforms, connect APIs, create agents, and deploy reusable productivity systems.",
    skills: ["No-Code", "AI Agents", "Automation", "API Integrations"],
    price: { oneMonth: 17, threeMonth: 39, sixMonth: 69 },
  },
  {
    slug: "prompt-engineering-for-business",
    title: "Prompt Engineering for Business",
    category: "AI/ML",
    instructor: "Kevin Roy",
    duration: "18h",
    lessons: 40,
    students: "5.4K",
    rating: 4.8,
    level: "All Levels",
    emoji: "✍️",
    img: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=800&auto=format&fit=crop",
    previewVideoUrl: "https://www.youtube.com/embed/nJ25yl34Uqw",
    shortDescription: "Scale your business productivity 10x with advanced AI prompt engineering.",
    longDescription: "Learn to automate customer service, content generation, and market analysis using high-level prompt engineering patterns.",
    skills: ["Prompt Design", "AI Automation", "Business AI", "LLMs"],
    price: { oneMonth: 24, threeMonth: 59, sixMonth: 99 },
  },
  {
    slug: "python-for-data-science",
    title: "Python for Data Science",
    category: "AI/ML",
    instructor: "Arjun Patel",
    duration: "55h",
    lessons: 110,
    students: "10.2K",
    rating: 4.9,
    level: "Beginner",
    emoji: "📊",
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop",
    previewVideoUrl: "https://www.youtube.com/embed/r-uOLxNrNk8",
    shortDescription: "Master Python libraries like Pandas, NumPy, and Scikit-Learn for data analysis.",
    longDescription: "A complete path from basic Python syntax to complex data modeling and visualization for data scientists.",
    skills: ["Python", "Pandas", "Scikit-Learn", "Data Viz"],
    price: { oneMonth: 34, threeMonth: 89, sixMonth: 159 },
  },
  {
    slug: "digital-marketing-mastery",
    title: "Digital Marketing Mastery",
    category: "Marketing",
    instructor: "Leah Kim",
    duration: "30h",
    lessons: 65,
    students: "8.7K",
    rating: 4.7,
    level: "All Levels",
    emoji: "🚀",
    img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop",
    previewVideoUrl: "https://www.youtube.com/embed/zMIt7w6QW7s",
    shortDescription: "Dominate SEO, Social Media, and Paid Ads in 2026.",
    longDescription: "Practical frameworks for growth marketing, funnel optimization, and scaling brands from scratch.",
    skills: ["SEO", "SMM", "Meta Ads", "Funnel Design"],
    price: { oneMonth: 19, threeMonth: 49, sixMonth: 89 },
  },
  {
    slug: "product-management-elite",
    title: "Product Management Elite",
    category: "Business",
    instructor: "Emily Watson",
    duration: "45h",
    lessons: 92,
    students: "4.1K",
    rating: 4.8,
    level: "Intermediate",
    emoji: "🏗️",
    img: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=800&auto=format&fit=crop",
    previewVideoUrl: "https://www.youtube.com/embed/4vA-_8x3r8U",
    shortDescription: "Master product strategy, roadmap prioritization, and data-driven execution.",
    longDescription: "Learn the frameworks used by top FAANG product managers to build and ship world-class products.",
    skills: ["Strategy", "Roadmapping", "Agile", "Stakeholder Mgmt"],
    price: { oneMonth: 39, threeMonth: 99, sixMonth: 179 },
  },
  // ── VIRTUAL COURSES (FOR SUBSCRIPTIONS) ───────────────────────────────────
  {
    slug: "plus-membership",
    title: "EduNova Plus Membership",
    category: "Development",
    instructor: "EduNova Team",
    duration: "Unlimited",
    lessons: 7000,
    students: "50K+",
    rating: 5.0,
    level: "All Levels",
    emoji: "🚀",
    isHidden: true,
    img: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    previewVideoUrl: "",
    shortDescription: "Unlimited access to 7,000+ courses, AI paths, and dedicated mentorship.",
    longDescription: "Your all-access pass to the entire EduNova catalog. Learn anything, anytime, with our most premium features enabled.",
    skills: ["All Skills", "Career Paths", "Certifications"],
    price: { oneMonth: 2099, threeMonth: 5999, sixMonth: 9999 },
  },
];

export function getCourseBySlug(slug: string) {
  return coursesData.find((course) => course.slug === slug);
}

